## Importando librerias

In [3]:
import numpy as np

### Creando listas

In [4]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

### Creando array

In [36]:
arr = np.array(lista) 

In [6]:
type(arr)

numpy.ndarray

In [60]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
matriz[0] 

[1, 2, 3]

### Indexing

In [41]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[1]

2

In [42]:
arr[0] + arr[5]

7

In [61]:
matriz[1,2] #Ingreso a la posicion tomando en cuenta filas y columnas, que seria lo mismo, eje x y eje y

6

In [62]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Slicing

In [67]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [31]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr[-3:]

array([7, 8, 9])

In [80]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
matriz[1:,0:2] 

array([[4, 5],
       [7, 8]])

In [91]:
matriz[1:,1] 

array([5, 8])

In [83]:
matriz[1:2,0:2] 

array([[4, 5]])

In [90]:
matriz[:1,2] 

array([3])

In [92]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
matriz[1:,1:]

array([[5, 6],
       [8, 9]])