### Importar librería

In [1]:
import numpy as np

In [36]:
# Recuperar el arreglo anterior
arr = np.arange(0,11)

# Resultado
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# Troceado de arreglos
trozo_de_arr = arr[0:6]

In [38]:
# Cambios 
trozo_de_arr[:] = 0

# Mostrar slice nuevamete
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [39]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [40]:
# Para obtener una copia es necesario usar el método copy()
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [41]:
arr_copy[:] = 100

In [42]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [43]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])