## Importando librerías

In [1]:
import numpy as np

### Arange

In [5]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
np.arange(0,20,2) #crea un arreglo del 1 al 20 que va de 2 en 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Zeros

In [12]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [46]:
np.ones((3,5,4,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
   

### Linspace

In [16]:
np.linspace(0,10,100) #nos da 100 datos del 0 al 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### Eye

In [22]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### Random

In [23]:
np.random.rand()

0.4380055219001796

In [24]:
np.random.rand(4)

array([0.89166309, 0.43338971, 0.00544237, 0.64486181])

In [25]:
np.random.rand(4,4)

array([[0.17827121, 0.25819469, 0.42726377, 0.3953623 ],
       [0.89004248, 0.72559526, 0.12740478, 0.30162795],
       [0.86542951, 0.484265  , 0.39012127, 0.04212081],
       [0.15950338, 0.49563491, 0.93983325, 0.02804427]])

In [36]:
np.random.randint(1,15)

10

In [42]:
np.random.randint(1,100,(10,10))

array([[46, 81, 58, 55, 78, 86, 93, 45, 50, 67],
       [ 9, 95, 46,  8, 41, 87,  5,  2, 33, 61],
       [91, 21, 37,  5, 79, 37, 84, 86, 61,  8],
       [30, 83, 62, 96,  9, 66, 35, 34, 73, 56],
       [23, 47, 60, 57, 79, 57, 11, 59, 78, 41],
       [33, 44, 80, 49, 86, 26, 88, 53, 63, 27],
       [43,  4, 85, 61, 59, 63, 49, 94, 73,  5],
       [80, 18, 71, 95, 32, 44, 14, 84,  6, 49],
       [ 8, 89, 55,  8,  4, 47, 82, 45, 83, 91],
       [73, 58, 52, 96, 52, 23, 48, 87, 13, 46]])