## Importar librería

In [2]:
import numpy as np

## Definiendo arrays

In [7]:
scalar = np.array(42)
print(scalar)
scalar.ndim #nos dice el numero de dimensiones

42


0

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [10]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [13]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[0,2,45]],[[1,2,3],[4,5,6],[7,8,9],[0,2,45]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 0  2 45]]]


3

## Agregar o eliminar dimensiones

In [14]:
vector = np.array([1,2,3],ndmin=10) #Le agrego mas dimensiones
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [20]:
expand = np.expand_dims(np.array([1,2,3]),axis=0) #expando una dimension
print(expand)
expand.ndim

[[1 2 3]]


2

In [22]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) #Elimina dimensiones
print(vector_2, vector_2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
