### Importando librerías

In [4]:
import numpy as np

In [5]:
arr = np.random.randint(1,20,10)

In [7]:
matriz = arr.reshape(2,5)
matriz

array([[17,  2, 15, 19,  4],
       [ 8,  1,  3,  4, 16]])

In [9]:
arr

array([17,  2, 15, 19,  4,  8,  1,  3,  4, 16])

### Max

In [10]:
arr.max()

19

In [11]:
matriz

array([[17,  2, 15, 19,  4],
       [ 8,  1,  3,  4, 16]])

In [16]:
matriz.max(1)

array([19, 16])

### Argmax

In [19]:
arr.argmax() #nos da el indice donde se encuentra el valor max

3

In [22]:
matriz.argmax(0)

array([0, 0, 0, 0, 1])

### Min

In [26]:
arr.min()

1

In [27]:
matriz.min(0)

array([8, 1, 3, 4, 4])

### Argmin

In [30]:
arr.argmin()

6

In [32]:
matriz.argmin(1)

array([1, 1])

### Ptp

In [36]:
arr

array([17,  2, 15, 19,  4,  8,  1,  3,  4, 16])

In [38]:
arr.ptp() #diferencia del valor mi al max

18

In [50]:
matriz

array([[17,  2, 15, 19,  4],
       [ 8,  1,  3,  4, 16]])

In [52]:
matriz.ptp(0)

array([ 9,  1, 12, 15, 12])

### Sort

In [74]:
arr.sort()
arr

array([ 1,  2,  3,  4,  4,  8, 15, 16, 17, 19])

### Percentile

In [75]:
np.percentile(arr,50)

6.0

### Median

In [76]:
np.median(arr)

6.0

In [77]:
np.median(matriz,1)

array([ 3., 16.])

### Standard Deviation (std)

In [79]:
np.std(arr) ** 2

44.89

### Variance (Var)

In [80]:
np.var(arr)

44.89

### Mean

In [82]:
np.mean(arr)

8.9

### Concatenate

In [117]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [119]:
np.concatenate((a,b),axis=0)

ValueError: ignored

In [121]:
print(a.ndim)
b.ndim

2


2

In [120]:
b = np.expand_dims(b,axis=0)

In [122]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [123]:
b

array([[5, 6]])

In [125]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [126]:
np.concatenate((a,b.T),axis=1) #La T es la transpuesta

array([[1, 2, 5],
       [3, 4, 6]])

### Transpuesta

In [129]:
b.T

array([[5],
       [6]])