### Importar librerías

In [1]:
import numpy as np 

In [3]:
arr = np.random.randint(1,10,(3,2))

### Shape

In [4]:
arr.shape

(3, 2)

In [9]:
arr

array([[7, 3],
       [8, 3],
       [2, 8]])

### Reshape

In [13]:
arr.reshape(1,6)

array([[7, 3, 8, 3, 2, 8]])

In [15]:
arr.reshape(2,3)

array([[7, 3, 8],
       [3, 2, 8]])

In [41]:
np.reshape(arr,(1,6))

array([[7, 3, 8, 3, 2, 8]])

In [40]:
arr

array([[7, 3],
       [8, 3],
       [2, 8]])

In [37]:
np.reshape(arr,(2,3),'C') #definiendo el tipo de lenguaje

array([[7, 3, 8],
       [3, 2, 8]])

In [38]:
np.reshape(arr,(2,3),'F') #en fortran

array([[7, 2, 3],
       [8, 3, 8]])

In [39]:
np.reshape(arr,(2,3),'A')# en mi sistema

array([[7, 3, 8],
       [3, 2, 8]])