### Importando librerias

In [23]:
import numpy as np #un unico tipo de dato se puede usar en el array

In [10]:
arr = np.array([1,2,3,4])
arr.dtype #Saber su tipo de dato

dtype('int64')

In [14]:
arr = np.array([1,2,3,4], dtype='float64') #Se cambia el tipo de dato
arr.dtype

dtype('float64')

In [15]:
arr

array([1., 2., 3., 4.])

### Cambiando tipo de datos

In [17]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [19]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_) #Lo cambia a tipo texto
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [21]:
arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [22]:
arr = np.array(['hola','1','2','3','4'])
arr = arr.astype(np.int8)
arr

ValueError: ignored